

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package paneles;

import com.sun.awt.AWTUtilities;
import java.util.ArrayList;
import java.util.HashSet;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import paneles.Estudiante;
import paneles.Curso;
import java.util.Timer;
import java.util.TimerTask;
/**
 *
 * @author doble
 */
public class pnlArreglos extends javax.swing.JPanel  {

   
    
    //Curso [] ListaCurso ;
    ArrayList<Curso> ListaCurso;
    DefaultListModel estudiantesPanel= new DefaultListModel();
    Timer timer=new Timer();
    TimerTask tarea= new TimerTask() {
        @Override
        public void run() {
            alertaMsg.setVisible(true);
        }
    };
   
    int indexCur;
    /**
     * Creates new form pnlArreglos
     */
    public pnlArreglos() {
        
        initComponents();
       
        estudiantesPanel = new DefaultListModel();
        indexCur=0; 
        ListaCurso=new ArrayList<Curso>();
        timer.schedule(tarea,500 );
        lista.setModel(estudiantesPanel);
        
    }

    
  
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        alertaMsg = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        botonSetTamañoCurso = new rsbuttom.RSButtonMetro();
        alertaMsgCurso = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        rSButtonMetro1 = new rsbuttom.RSButtonMetro();
        jLabel4 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        ventanaAgregarDatos = new javax.swing.JFrame();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        adicionalesN1 = new javax.swing.JTextField();
        adicionalesN2 = new javax.swing.JTextField();
        adicionalesN3 = new javax.swing.JTextField();
        adicionalesN4 = new javax.swing.JTextField();
        adicionalesDir = new javax.swing.JTextField();
        adicionalesTelf = new javax.swing.JTextField();
        adicionalesEmail = new javax.swing.JTextField();
        adicionalesId = new javax.swing.JTextField();
        okDatosAdicionales = new rsbuttom.RSButtonMetro();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        ventanaFoto = new javax.swing.JFrame();
        buscadorFichero = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputApellidos = new javax.swing.JTextPane();
        cantidadEstudiantes = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addDate = new javax.swing.JButton();
        buildList = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        resetList = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        editionOk = new javax.swing.JButton();
        cambiarButton = new javax.swing.JRadioButton();
        borrarButton = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        nombreCurso = new javax.swing.JTextField();
        listasBox = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        inputNombres = new javax.swing.JTextPane();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        datoId = new javax.swing.JLabel();
        datoEs = new javax.swing.JLabel();
        datoDir = new javax.swing.JLabel();
        datoEmail = new javax.swing.JLabel();
        datoProme = new javax.swing.JLabel();
        datoTelf = new javax.swing.JLabel();
        fotoLabel = new javax.swing.JLabel();
        setFoto = new rsbuttom.RSButtonMetro();
        datosAdicionales = new javax.swing.JButton();

        alertaMsg.setBackground(new java.awt.Color(255, 102, 102));
        alertaMsg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        alertaMsg.setLocation(new java.awt.Point(700, 400));
        alertaMsg.setMinimumSize(new java.awt.Dimension(450, 250));

        jTextPane2.setBackground(new java.awt.Color(255, 204, 51));
        jTextPane2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextPane2.setForeground(new java.awt.Color(255, 255, 255));
        jTextPane2.setText("INSTRUCTIVO:\n✅ TODO CURSO DEBE SER INGRESADO EN MAYUSCULA SOSTENIDA.\n✅ TODO NOMBRE DEBE SER INGRESADO EN MAYUSCULA SOSTENIDA.\n");
        jScrollPane5.setViewportView(jTextPane2);

        botonSetTamañoCurso.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonSetTamañoCurso.setText("OK");
        botonSetTamañoCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSetTamañoCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout alertaMsgLayout = new javax.swing.GroupLayout(alertaMsg.getContentPane());
        alertaMsg.getContentPane().setLayout(alertaMsgLayout);
        alertaMsgLayout.setHorizontalGroup(
            alertaMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alertaMsgLayout.createSequentialGroup()
                .addGroup(alertaMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(alertaMsgLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(alertaMsgLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(botonSetTamañoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        alertaMsgLayout.setVerticalGroup(
            alertaMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alertaMsgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonSetTamañoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        alertaMsgCurso.setBackground(new java.awt.Color(255, 102, 102));
        alertaMsgCurso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        alertaMsgCurso.setLocation(new java.awt.Point(700, 400));
        alertaMsgCurso.setMinimumSize(new java.awt.Dimension(400, 150));
        alertaMsgCurso.setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));
        jPanel3.setMinimumSize(new java.awt.Dimension(400, 150));
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 150));

        jTextPane1.setBackground(new java.awt.Color(255, 153, 153));
        jTextPane1.setBorder(null);
        jTextPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextPane1.setText("Debe ingresar otro nombre de curso que no esté en la lista.");
        jTextPane1.setFocusable(false);
        jScrollPane2.setViewportView(jTextPane1);

        rSButtonMetro1.setText("ok");
        rSButtonMetro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro1ActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/sirena.png"))); // NOI18N

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/sirena.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addGap(55, 55, 55))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(rSButtonMetro1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rSButtonMetro1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout alertaMsgCursoLayout = new javax.swing.GroupLayout(alertaMsgCurso.getContentPane());
        alertaMsgCurso.getContentPane().setLayout(alertaMsgCursoLayout);
        alertaMsgCursoLayout.setHorizontalGroup(
            alertaMsgCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        alertaMsgCursoLayout.setVerticalGroup(
            alertaMsgCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alertaMsgCursoLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        ventanaAgregarDatos.setLocation(new java.awt.Point(700, 400));
        ventanaAgregarDatos.setMinimumSize(new java.awt.Dimension(719, 245));
        ventanaAgregarDatos.setUndecorated(true);

        jLabel16.setText("Nota 3");

        jLabel17.setText("Dirección");

        jLabel18.setText("Nota 4");

        jLabel19.setText("Telefono");

        jLabel20.setText("Id");

        jLabel21.setText("Correo");

        jLabel22.setText("Nota 1");

        jLabel23.setText("Nota 2");

        okDatosAdicionales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/verificacion.png"))); // NOI18N
        okDatosAdicionales.setText("OK");
        okDatosAdicionales.setColorBorde(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        okDatosAdicionales.setColorHover(new java.awt.Color(255, 204, 0));
        okDatosAdicionales.setColorNormal(new java.awt.Color(204, 204, 204));
        okDatosAdicionales.setColorPressed(new java.awt.Color(240, 240, 240));
        okDatosAdicionales.setColorTextHover(new java.awt.Color(0, 0, 0));
        okDatosAdicionales.setColorTextNormal(new java.awt.Color(0, 0, 0));
        okDatosAdicionales.setColorTextPressed(new java.awt.Color(0, 0, 0));
        okDatosAdicionales.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        okDatosAdicionales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okDatosAdicionalesActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 51, 51));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/chulitos.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ventanaAgregarDatosLayout = new javax.swing.GroupLayout(ventanaAgregarDatos.getContentPane());
        ventanaAgregarDatos.getContentPane().setLayout(ventanaAgregarDatosLayout);
        ventanaAgregarDatosLayout.setHorizontalGroup(
            ventanaAgregarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaAgregarDatosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(ventanaAgregarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventanaAgregarDatosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(ventanaAgregarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addGroup(ventanaAgregarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel17)
                                .addComponent(jLabel21)
                                .addComponent(jLabel20)))
                        .addGap(18, 18, 18)
                        .addGroup(ventanaAgregarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(adicionalesDir)
                            .addComponent(adicionalesTelf)
                            .addComponent(adicionalesEmail)
                            .addComponent(adicionalesId, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(ventanaAgregarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(ventanaAgregarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adicionalesN2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adicionalesN1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adicionalesN3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adicionalesN4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ventanaAgregarDatosLayout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(okDatosAdicionales, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ventanaAgregarDatosLayout.setVerticalGroup(
            ventanaAgregarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ventanaAgregarDatosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(ventanaAgregarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventanaAgregarDatosLayout.createSequentialGroup()
                        .addGroup(ventanaAgregarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(adicionalesDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(ventanaAgregarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(adicionalesTelf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(ventanaAgregarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adicionalesId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)))
                    .addGroup(ventanaAgregarDatosLayout.createSequentialGroup()
                        .addGroup(ventanaAgregarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(adicionalesN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(ventanaAgregarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adicionalesN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addGroup(ventanaAgregarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ventanaAgregarDatosLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(ventanaAgregarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(adicionalesN3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(ventanaAgregarDatosLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(ventanaAgregarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(adicionalesN4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(ventanaAgregarDatosLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(ventanaAgregarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(adicionalesEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(okDatosAdicionales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        buscadorFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscadorFicheroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ventanaFotoLayout = new javax.swing.GroupLayout(ventanaFoto.getContentPane());
        ventanaFoto.getContentPane().setLayout(ventanaFotoLayout);
        ventanaFotoLayout.setHorizontalGroup(
            ventanaFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaFotoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buscadorFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ventanaFotoLayout.setVerticalGroup(
            ventanaFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buscadorFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setBackground(new java.awt.Color(255, 102, 102));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMinimumSize(new java.awt.Dimension(968, 667));
        setPreferredSize(new java.awt.Dimension(928, 627));

        jScrollPane1.setViewportView(inputApellidos);

        cantidadEstudiantes.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel1.setText("Ingrese Cupos de Estudiantes");

        jLabel2.setText("Ingrese los nombres ");

        jLabel3.setText("Seleccione el estudiante ");

        addDate.setText("Agregar Estudiante");
        addDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDateActionPerformed(evt);
            }
        });

        buildList.setText("Crear Lista");
        buildList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buildListActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Lista Actual");

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));

        resetList.setText("Reiniciar Lista");
        resetList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetListActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(resetList)
                        .addGap(70, 70, 70))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resetList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        editionOk.setText("Cambiar");
        editionOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editionOkActionPerformed(evt);
            }
        });

        cambiarButton.setBackground(new java.awt.Color(255, 102, 102));
        buttonGroup1.add(cambiarButton);
        cambiarButton.setText("Cambiar");

        borrarButton.setBackground(new java.awt.Color(255, 102, 102));
        buttonGroup1.add(borrarButton);
        borrarButton.setText("Borrar");
        borrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Nombre de Curso");

        listasBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listasBoxItemStateChanged(evt);
            }
        });
        listasBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listasBoxMouseClicked(evt);
            }
        });
        listasBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listasBoxActionPerformed(evt);
            }
        });

        lista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lista.setSelectionForeground(new java.awt.Color(255, 204, 51));
        lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaMouseClicked(evt);
            }
        });
        lista.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lista);

        jLabel7.setText("Ingrese los apellidos ");

        jScrollPane4.setViewportView(inputNombres);

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel8.setText("Datos");

        jLabel9.setText("Estudiante: ");

        jLabel10.setText("Promedio de Notas");

        jLabel11.setText("Dirección:");

        jLabel12.setText("Telefono:");

        jLabel13.setText("Email:");

        jLabel14.setText("Id:");

        datoId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        datoEs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        datoDir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        datoEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        datoProme.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        datoProme.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        datoTelf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        fotoLabel.setBackground(new java.awt.Color(255, 255, 255));
        fotoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fotoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/usuario.png"))); // NOI18N
        fotoLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        setFoto.setForeground(new java.awt.Color(0, 0, 0));
        setFoto.setText("Cambiar foto");
        setFoto.setColorHover(new java.awt.Color(255, 204, 51));
        setFoto.setColorNormal(new java.awt.Color(153, 153, 153));
        setFoto.setColorTextHover(new java.awt.Color(51, 51, 51));
        setFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setFotoActionPerformed(evt);
            }
        });

        datosAdicionales.setText("Añadir Datos Adicionales");
        datosAdicionales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datosAdicionalesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(datoProme, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel9))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(datoEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(datoDir, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                .addComponent(datoEs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(datoTelf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(datosAdicionales)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(datoId, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fotoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(setFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)))
                .addGap(96, 96, 96))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(datosAdicionales)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(datoDir, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)
                                .addGap(14, 14, 14)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(datoEs, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(datoTelf, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(datoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(datoProme, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(fotoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(setFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addComponent(datoId, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(90, 90, 90)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(115, 115, 115)
                                .addComponent(listasBox, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(155, 155, 155)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(cantidadEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(buildList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(borrarButton)
                            .addComponent(cambiarButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editionOk))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(541, 541, 541)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3))
                        .addGap(24, 24, 24)))
                .addGap(96, 96, 96))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator3)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreCurso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cantidadEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buildList)))))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(listasBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cambiarButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(borrarButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(editionOk)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addDate)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    /**public void esRepetido(int items){
    for(int i=0 ; i>items; ++i){
                            
                           JOptionPane.showMessageDialog(null, pivoteBox);
                         
                           if(inputNombreLista==listasBox.getItemAt(i)){
                              nombreRepetido=true;
                              i=pivoteBox;
                           }

                        }
    }**/
    private void buildListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buildListActionPerformed
        String inputNombreLista;
        String inputCantidadEstudiantes, nombreBuscado; 
        
        int pivoteBox;
        
        boolean nombreRepetido=false;
        
        nombreRepetido=false;
        inputNombreLista= nombreCurso.getText();
        inputCantidadEstudiantes = cantidadEstudiantes.getValue().toString();
        pivoteBox=listasBox.getItemCount();
        
        int tamañoLista=Integer.parseInt(inputCantidadEstudiantes);
       
                do{

                            nombreBuscado=listasBox.getItemAt(pivoteBox);

                            if(inputNombreLista.equals(nombreBuscado)){

                                                  nombreRepetido=true;

                                               }
                            pivoteBox--;
                }while(pivoteBox >=0);
          
            
            if(nombreRepetido==true){
            alertaMsgCurso.setVisible(true);
            
            }else{
            
              if(inputNombreLista.length()>2){    
           
                ListaCurso.add(new Curso(inputNombreLista)); 
                ListaCurso.get(indexCur).setTamañoCurso(tamañoLista);
                listasBox.addItem(ListaCurso.get(indexCur).getNombreCurso());
                nombreCurso.setText("");
                cantidadEstudiantes.setValue(1);
                JOptionPane.showMessageDialog(null,"Curso "+inputNombreLista+" agregado exitosamente");
                
                pivoteBox++;
                indexCur++;
        
        }else{
        JOptionPane.showMessageDialog(null,"El curso debe contener mas de dos (2) caracteres");
        nombreCurso.setText("");
        }
            }
             
      
        
        
    }//GEN-LAST:event_buildListActionPerformed

    private void resetListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetListActionPerformed
         //DefaultListModel limpiar = limpiarJList();
    }//GEN-LAST:event_resetListActionPerformed
// JOptionPane.showMessageDialog(null, nombreBuscado);
    private void listaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaMouseClicked
      String icono,id_changed, promedio;
        int cursoIndex, estudianteSelect;
        
        
        
        cursoIndex=listasBox.getSelectedIndex();
        estudianteSelect= lista.getSelectedIndex();
     
        estudiantesPanel=ListaCurso.get(cursoIndex).estudiantes;
        lista.setModel(estudiantesPanel);
        
        icono= ListaCurso.get(cursoIndex).Estudi.get(estudianteSelect).getFoto();
        fotoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource(icono)));
        
        id_changed=String.valueOf(ListaCurso.get(cursoIndex).Estudi.get(estudianteSelect).getId());
        promedio=String.valueOf(ListaCurso.get(cursoIndex).Estudi.get(estudianteSelect).getPromedio());
                
        datoDir.setText(ListaCurso.get(cursoIndex).Estudi.get(estudianteSelect).getDireccion());
        datoEmail.setText(ListaCurso.get(cursoIndex).Estudi.get(estudianteSelect).getEmail());
        datoEs.setText(ListaCurso.get(cursoIndex).Estudi.get(estudianteSelect).toString());
        datoId.setText(id_changed);
        datoTelf.setText(ListaCurso.get(cursoIndex).Estudi.get(estudianteSelect).getTelefono());
        datoProme.setText(promedio);
        
                
    }//GEN-LAST:event_listaMouseClicked

   
    private void addDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDateActionPerformed
        
        String nombre, apellido;
        int cursoIndex, cuposDato, pivote;
        
        /**
         *OBTJEEMOS VALORES DE LOS TEXTFIELD PRESENTES Y DEL JBOX DE SELECCION DE LOS CURSOS
        **/
        nombre =  inputNombres.getText();
        apellido= inputApellidos.getText();
        cursoIndex=listasBox.getSelectedIndex();
        pivote=0;
        
        /* ****************************
        VERIFICAMOS SI EL NOMBRE DEL TEXT FIELD SE ENCUENTRA PRESENTE EN LA LISTA
        ********************************
        */
        
        cuposDato=ListaCurso.get(cursoIndex).Estudi.size();
         

        do{
            
            if(cuposDato==0){
            
            ListaCurso.get(cursoIndex).Estudi.add(new Estudiante(nombre,apellido,ListaCurso.get(cursoIndex).getNombreCurso()));
            ListaCurso.get(cursoIndex).estudiantes.addElement(nombre+apellido); // AGREGAMOS EL NOMBRE DEL ESTUDIANTE AL DEFAUL_LIST_MODEL ESTUDIANTES PARA RELACIONARLO CON ESTUDIANTESPANEL 
             // Y FINALMENTE AGREGARLO AL JLIST DESDE INITCOMPONENTS AL DAR UN SETMODELS AL JLIST "LISTA"
            estudiantesPanel = ListaCurso.get(cursoIndex).estudiantes; // IGUALAMOS LA LISTA CON EL MODELO PANEL
            lista.setModel(estudiantesPanel);
            }else{
                    if(nombre.equals(ListaCurso.get(cursoIndex).Estudi.get(pivote).toString())){
                            JOptionPane.showMessageDialog(null,"El nombre ya se encuentra en la Lista");
                            inputNombres.setText("");
                            inputApellidos.setText("");
                    }else{

                            ListaCurso.get(cursoIndex).Estudi.add(new Estudiante(nombre,apellido,ListaCurso.get(cursoIndex).getNombreCurso()));
                            ListaCurso.get(cursoIndex).estudiantes.addElement(nombre+apellido); // AGREGAMOS EL NOMBRE DEL ESTUDIANTE AL DEFAUL_LIST_MODEL ESTUDIANTES PARA RELACIONARLO CON ESTUDIANTESPANEL 
                             // Y FINALMENTE AGREGARLO AL JLIST DESDE INITCOMPONENTS AL DAR UN SETMODELS AL JLIST "LISTA"
                            estudiantesPanel = ListaCurso.get(cursoIndex).estudiantes; // IGUALAMOS LA LISTA CON EL MODELO PANEL

                    }
            }
            
            
            pivote++;
        }while(pivote==cuposDato);
       
        
    }//GEN-LAST:event_addDateActionPerformed

    private void editionOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editionOkActionPerformed
        
        if(cambiarButton.isSelected()){
        int elec= lista.getSelectedIndex();
        String info = nuevoNombre.getText();
        estudiantes.set(elec, info);
            
        }
        if(borrarButton.isSelected()){
         int elec= lista.getSelectedIndex();
         estudiantes.remove(elec);
        }
        
       
    }//GEN-LAST:event_editionOkActionPerformed

    private void borrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_borrarButtonActionPerformed

    private void listaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaValueChanged
        
        
        
        
    }//GEN-LAST:event_listaValueChanged

    private void datosAdicionalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datosAdicionalesActionPerformed
        
        ventanaAgregarDatos.setVisible(true);

    }//GEN-LAST:event_datosAdicionalesActionPerformed

    private void rSButtonMetro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro1ActionPerformed
        //alerta msg CURSO EXISTENTE
        alertaMsgCurso.setVisible(false);
        nombreCurso.setText("");
        alertaMsgCurso.dispose();
        
    }//GEN-LAST:event_rSButtonMetro1ActionPerformed

    private void okDatosAdicionalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okDatosAdicionalesActionPerformed
        int cursoIndex,estudianteIndex;
        cursoIndex=listasBox.getSelectedIndex();
        estudianteIndex= lista.getSelectedIndex();
         String direccion, email, telf;
         int id_ad;
         
         JOptionPane.showMessageDialog(null,estudianteIndex);
                
       direccion=adicionalesDir.getText();
       email=adicionalesEmail.getText();
       telf=adicionalesTelf.getText();
       id_ad=Integer.parseInt(adicionalesId.getText());
       
            
            ListaCurso.get(cursoIndex).Estudi.get(estudianteIndex).setDireccion(direccion);
            ListaCurso.get(cursoIndex).Estudi.get(estudianteIndex).setEmail(email);
            ListaCurso.get(cursoIndex).Estudi.get(estudianteIndex).setTelefono(telf);
            ListaCurso.get(cursoIndex).Estudi.get(estudianteIndex).setId(id_ad);
            

                JOptionPane.showMessageDialog(null,"Datos Añadidos correctamente en el estudiante: "+lista.getName());
                
                ventanaAgregarDatos.setVisible(false);
                ventanaAgregarDatos.dispose();
  
        
    }//GEN-LAST:event_okDatosAdicionalesActionPerformed

    private void listasBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listasBoxMouseClicked
        int cursoIndex,estudianteIndex, pivote;
        cursoIndex=listasBox.getSelectedIndex();
        
    }//GEN-LAST:event_listasBoxMouseClicked

    private void listasBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listasBoxActionPerformed
       int cursoIndex,estudianteIndex, pivote;
        cursoIndex=listasBox.getSelectedIndex();
        
    }//GEN-LAST:event_listasBoxActionPerformed

    private void buscadorFicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscadorFicheroActionPerformed
       
       int cursoIndex, estudianteSelect;
       ventanaFoto.setVisible(true);
       
       FileNameExtensionFilter filter = new FileNameExtensionFilter( "JPG, PNG & GIF Images", "jpg", "gif","PNG");
       buscadorFichero.setFileFilter(filter);
       int returnVal;
        returnVal = buscadorFichero.showDialog(jPanel1, TOOL_TIP_TEXT_KEY);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
             buscadorFichero.showDialog(null, "Escojio este archivo: " + buscadorFichero.getSelectedFile().getName());
             cursoIndex=listasBox.getSelectedIndex();
             estudianteSelect=lista.getSelectedIndex();
             ListaCurso.get(cursoIndex).Estudi.get(estudianteSelect).setFoto(buscadorFichero.getSelectedFile().getName());
        }
        
       
       
    }//GEN-LAST:event_buscadorFicheroActionPerformed
    
    private void setFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setFotoActionPerformed
        int estudianteSelect, cursoIndex;
        estudianteSelect=lista.getSelectedIndex();
        cursoIndex=listasBox.getComponentCount();
        if((estudianteSelect ==0) || (cursoIndex==0)){
            fotoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource(icono)));
        }else{
        ventanaFoto.setVisible(true);
        }    
        
    }//GEN-LAST:event_setFotoActionPerformed

    private void botonSetTamañoCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSetTamañoCursoActionPerformed

        alertaMsg.setVisible(false);
        alertaMsg.dispose();
    }//GEN-LAST:event_botonSetTamañoCursoActionPerformed

    private void listasBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listasBoxItemStateChanged
        int cursoIndex, estudianteIndex;
        
        cursoIndex=listasBox.getSelectedIndex();
        
        estudiantesPanel=ListaCurso.get(cursoIndex).estudiantes;
        lista.setModel(estudiantesPanel);
    }//GEN-LAST:event_listasBoxItemStateChanged
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDate;
    public static javax.swing.JTextField adicionalesDir;
    public static javax.swing.JTextField adicionalesEmail;
    public static javax.swing.JTextField adicionalesId;
    public static javax.swing.JTextField adicionalesN1;
    public static javax.swing.JTextField adicionalesN2;
    public static javax.swing.JTextField adicionalesN3;
    public static javax.swing.JTextField adicionalesN4;
    public static javax.swing.JTextField adicionalesTelf;
    private javax.swing.JDialog alertaMsg;
    private javax.swing.JDialog alertaMsgCurso;
    private javax.swing.JRadioButton borrarButton;
    private rsbuttom.RSButtonMetro botonSetTamañoCurso;
    private javax.swing.JButton buildList;
    public javax.swing.JFileChooser buscadorFichero;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cambiarButton;
    private javax.swing.JSpinner cantidadEstudiantes;
    public static javax.swing.JLabel datoDir;
    public static javax.swing.JLabel datoEmail;
    public static javax.swing.JLabel datoEs;
    public static javax.swing.JLabel datoId;
    public static javax.swing.JLabel datoProme;
    public static javax.swing.JLabel datoTelf;
    private javax.swing.JButton datosAdicionales;
    private javax.swing.JButton editionOk;
    private javax.swing.JLabel fotoLabel;
    private javax.swing.JTextPane inputApellidos;
    private javax.swing.JTextPane inputNombres;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JList<String> lista;
    private javax.swing.JComboBox<String> listasBox;
    private javax.swing.JTextField nombreCurso;
    private rsbuttom.RSButtonMetro okDatosAdicionales;
    private rsbuttom.RSButtonMetro rSButtonMetro1;
    private javax.swing.JButton resetList;
    private rsbuttom.RSButtonMetro setFoto;
    private javax.swing.JFrame ventanaAgregarDatos;
    private javax.swing.JFrame ventanaFoto;
    // End of variables declaration//GEN-END:variables
}
