/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

/**
 *
 * @author doble
 */
public class InfoCalculadora extends javax.swing.JPanel {

    /**
     * Creates new form InfoCalculadora
     */
    public InfoCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        jTextPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextPane1.setText("\n\n\nSe quiere crear una aplicación para administrar las ventas de una empresa de comidas rapidas. La empresa cuenta con tres locales a traves de los cuales se vendentres productos: hamburguesas, empanadas y perros calientes Los precios de los productos son los siguientes: Hamburguesas: $5.000 pesos Empanadas: $800pesos Perros Calientes: $4.000 pesos \nLa aplicaciondebe permitir: \n(1) Registrar una venta en alguno de los locales.\n(2) Mostrar la información detallada de cada local, Numero de Ventas, Cantidad de productos vendidos y el Total en pesos de las ventas\n(3) Mostrar un consolidado total de la información de todos los locales (Total Ventas;Total de Cantidad de productos vendidos y el calculo del precio promedio por producto;según el total de ventas y el total de cantida\nd). Adicionalmente, la aplicación debe;permitir reiniciar los valores de las ventas por local, dejando todos sus valores en cero.");
        jScrollPane2.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
